version: "2.1"
orbs:
  node: circleci/node@5.0.0
jobs:
  install:
    executor: node/default
    steps:
      - run: npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
workflows:
  test_my_app:
    jobs:
      - install
