version: "2.1"
orbs:
  node: circleci/node@5.0.0
jobs:
  install_build:
    executor: node/default
    steps:
      - checkout
      - run: npm install -g npm@latest
      - node/install-packages:
          cache-path: node_modules/
          override-ci-command: npm install
      - run: npm run build
      - store_artifacts:
          path: out/
  tests:
    executor: node/default
    steps:
      - run:
          name: lint
          command: npm run lint
      - run:
          name: prettier
          command: npm run prettier
      - run:
          name: test
          command: npm run test
      
workflows:
  test_my_app:
    jobs:
      - install_build
      - tests
