version: "2.1"
orbs:
  node: circleci/node@5.0.0
jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - run: npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
  build:
    executor: node/default
    steps:
      - run: npm run build
      - store_artifacts:
          path: /out/

workflows:
  test_my_app:
    jobs:
      - install
      - build
