name: miniprojeto CI/CD

on:
  push:
    branches: [ main ]


jobs:
  install_and_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #começa o install
      - run: npm install
    
      #começa a build
      - run: npm run build
      #produz artefacto
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out folder
          path: |
            out/

  tests: 
    needs: install_and_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
      
      - run: npm run lint
      - run: npm run prettier
      - run: npm run test

      


  

  
  


    