name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  install_and_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #começa o install
      - run: npm install

      #começa a build
      - run: npm run build
      #produz artefacto
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out folder
          path: |
            out/

  tests: 
    needs: install_and_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - run: npm run lint
      - run: npm run prettier
      - run: npm run test

      


  

  
  


    